# Generated by Django 5.1.4 on 2025-01-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piloto', models.CharField(max_length=100)),
                ('copiloto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_carga', models.CharField(choices=[('pasajeros', 'Pasajeros'), ('material', 'Material'), ('mixto', 'Mixto')], max_length=20)),
                ('descripcion_carga', models.TextField(blank=True, null=True)),
                ('tipo_cobro', models.CharField(choices=[('hora_vuelo', 'Por Hora de Vuelo'), ('destino', 'Por Destino'), ('cortesia', 'Cortesía')], max_length=20)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('EUR', 'Euros'), ('ORO', 'Gramos de Oro')], max_length=10)),
                ('monto_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField()),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='registro_vuelos.avion')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
            },
        ),
    ]
