# Generated by Django 5.1.4 on 2025-01-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0002_vuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='tipo_cobro',
            field=models.CharField(choices=[('hora_vuelo', 'Por Hora de Vuelo'), ('destino', 'Por Destino'), ('colaboracion', 'Colaboración')], max_length=20),
        ),
    ]
