# Generated by Django 5.1.4 on 2025-01-06 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0003_alter_vuelo_tipo_cobro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto')], max_length=20, verbose_name='Tipo de empleado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.AlterModelOptions(
            name='avion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vuelo',
            options={},
        ),
        migrations.RemoveField(
            model_name='avion',
            name='capacidad_carga',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='tipo_cobro',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='destinos',
            field=models.TextField(blank=True, help_text='Lista de destinos separados por comas', null=True, verbose_name='Destinos'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='gastos',
            field=models.TextField(blank=True, help_text='Lista de gastos separados por comas', null=True, verbose_name='Gastos adicionales'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='horas_horometro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Horas del horómetro'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='horas_vuelo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Horas de vuelo'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='tipo_cobro_copiloto',
            field=models.CharField(blank=True, choices=[('Hora Vuelo', 'Por Hora de Vuelo'), ('Destino', 'Por Destino'), ('Colaboración', 'Colaboración')], default='Colaboración', max_length=15, null=True, verbose_name='Tipo de cobro del copiloto'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='tipo_cobro_piloto',
            field=models.CharField(choices=[('Hora Vuelo', 'Por Hora de Vuelo'), ('Destino', 'Por Destino'), ('Colaboración', 'Colaboración')], default='Hora Vuelo', max_length=15, verbose_name='Tipo de cobro del piloto'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='capacidad_pasajeros',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avion',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avion',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='avion',
            name='matricula',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='avion',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='avion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='registro_vuelos.avion', verbose_name='Avión'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='descripcion_carga',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la carga'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del vuelo'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares'), ('EUR', 'Euros'), ('GOLD', 'Gramos de Oro'), ('OTH', 'Otra')], max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='monto_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto del pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='tipo_carga',
            field=models.CharField(choices=[('Pasajeros', 'Pasajeros'), ('Material', 'Material'), ('Mixto', 'Mixto')], max_length=10, verbose_name='Tipo de carga'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='copiloto',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'copiloto'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_copiloto', to='registro_vuelos.empleado', verbose_name='Copiloto'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='piloto',
            field=models.ForeignKey(limit_choices_to={'tipo': 'piloto'}, on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_piloto', to='registro_vuelos.empleado', verbose_name='Piloto'),
        ),
    ]
