# Generated by Django 5.1.4 on 2025-01-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0004_empleado_alter_avion_options_alter_vuelo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avion',
            options={'verbose_name': 'Avión', 'verbose_name_plural': 'Aviones'},
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='monto_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto del pago'),
        ),
    ]
