# Generated by Django 5.1.4 on 2025-01-06 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0005_alter_avion_options_alter_vuelo_monto_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='descripcion_carga',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='destinos',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='gastos',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='horas_horometro',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='horas_vuelo',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='monto_pago',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='tipo_carga',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='tipo_cobro_copiloto',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='tipo_cobro_piloto',
        ),
        migrations.AddField(
            model_name='avion',
            name='capacidad_carga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='horas_totales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Horas totales del vuelo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='copiloto',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'copiloto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vuelos_copiloto', to='registro_vuelos.empleado'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='piloto',
            field=models.ForeignKey(limit_choices_to={'tipo': 'piloto'}, on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_piloto', to='registro_vuelos.empleado'),
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('horometro_inicio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('horometro_fin', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='registro_vuelos.vuelo')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
            },
        ),
    ]
