# Generated by Django 5.1.4 on 2025-01-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0006_alter_vuelo_options_remove_vuelo_descripcion_carga_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='destino',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vuelo',
            options={},
        ),
        migrations.RemoveField(
            model_name='destino',
            name='horometro_fin',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='horometro_inicio',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='vuelo',
        ),
        migrations.AddField(
            model_name='destino',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
        migrations.AddField(
            model_name='destino',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del destino'),
        ),
        migrations.AddField(
            model_name='destino',
            name='nombre',
            field=models.CharField(default='Destino sin nombre', max_length=100, unique=True, verbose_name='Nombre del destino'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='destinos',
            field=models.ManyToManyField(related_name='vuelos', to='registro_vuelos.destino', verbose_name='Destinos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto')], max_length=20, verbose_name='Tipo de empleado'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='horas_totales',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas totales de vuelo'),
        ),
    ]
