# Generated by Django 5.1.4 on 2025-01-06 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0007_alter_avion_options_alter_destino_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avion',
            options={'verbose_name': 'Avión', 'verbose_name_plural': 'Aviones'},
        ),
        migrations.AlterModelOptions(
            name='destino',
            options={'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='vuelo',
            options={'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='destinos',
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='horas_totales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Horas totales de vuelo'),
        ),
        migrations.CreateModel(
            name='TramoVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horometro_inicio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horómetro de salida')),
                ('horometro_fin', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horómetro de llegada')),
                ('horas_tramo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Horas del tramo')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_llegada', to='registro_vuelos.destino', verbose_name='Aeropuerto de llegada')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_salida', to='registro_vuelos.destino', verbose_name='Aeropuerto de salida')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='registro_vuelos.vuelo', verbose_name='Vuelo')),
            ],
            options={
                'verbose_name': 'Tramo de Vuelo',
                'verbose_name_plural': 'Tramos de Vuelo',
            },
        ),
    ]
