# Generated by Django 5.1.4 on 2025-01-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0008_alter_avion_options_alter_destino_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramovuelo',
            name='horas_tramo',
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='horometro_fin',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Horómetro de llegada'),
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='horometro_inicio',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Horómetro de salida'),
        ),
    ]
