# Generated by Django 5.1.4 on 2025-01-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0009_remove_tramovuelo_horas_tramo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='horas_totales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas totales de vuelo'),
        ),
    ]
