# Generated by Django 5.1.4 on 2025-01-07 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0010_alter_vuelo_horas_totales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='horas_totales',
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='registro_vuelos.destino'),
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origenes', to='registro_vuelos.destino'),
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='registro_vuelos.vuelo'),
        ),
    ]
