# Generated by Django 5.1.4 on 2025-01-07 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0011_remove_vuelo_horas_totales_alter_tramovuelo_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramovuelo',
            name='horas_tramo',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_llegada', to='registro_vuelos.destino'),
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='horometro_fin',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='horometro_inicio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_salida', to='registro_vuelos.destino'),
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_vuelo', to='registro_vuelos.vuelo'),
        ),
    ]
