# Generated by Django 5.1.4 on 2025-01-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0013_vuelo_horas_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='horas_colaboracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas acumuladas por colaboración'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horas_por_destino',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas acumuladas por destino'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horas_por_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas acumuladas por hora'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horas_totales',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total de horas voladas'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='tipo_cobro',
            field=models.CharField(choices=[('por_hora', 'Por Hora'), ('por_destino', 'Por Destino'), ('colaboracion', 'Colaboración')], default='por_hora', max_length=15, verbose_name='Tipo de cobro del vuelo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de empleado'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='horas_totales',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas totales de vuelo'),
        ),
    ]
