# Generated by Django 5.1.4 on 2025-01-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0014_empleado_horas_colaboracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='horas_totales',
        ),
    ]
