# Generated by Django 5.1.4 on 2025-01-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0015_remove_vuelo_horas_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='horas_totales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Horas totales de vuelo'),
        ),
    ]
