# Generated by Django 5.1.4 on 2025-01-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0016_vuelo_horas_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='total_costo_por_destino',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo acumulado por destino'),
        ),
        migrations.CreateModel(
            name='DestinoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por destino')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_destinos', to='registro_vuelos.destino', verbose_name='Destino')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_destinos', to='registro_vuelos.empleado', verbose_name='Empleado (Piloto o Copiloto)')),
            ],
            options={
                'unique_together': {('empleado', 'destino')},
            },
        ),
    ]
