# Generated by Django 5.1.4 on 2025-01-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0017_empleado_total_costo_por_destino_destinocosto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={},
        ),
    ]
