# Generated by Django 5.1.4 on 2025-01-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0018_alter_vuelo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='bitacora',
            field=models.CharField(default='SIN_BITACORA', help_text='Número alfanumérico único para identificar este vuelo.', max_length=20, unique=True, verbose_name='Número de Bitácora'),
        ),
    ]
