# Generated by Django 5.1.4 on 2025-01-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0019_vuelo_bitacora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cliente')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Información de Contacto')),
                ('deuda_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deuda Total en USD')),
                ('deuda_gramos_oro', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deuda en Gramos de Oro')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='InventarioOro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramos_disponibles', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gramos Disponibles')),
                ('gramos_en_fundicion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gramos en Fundición')),
                ('precio_por_gramo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por Gramo en USD')),
                ('valor_total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total en USD')),
            ],
            options={
                'verbose_name': 'Inventario de Oro',
                'verbose_name_plural': 'Inventarios de Oro',
            },
        ),
        migrations.AddField(
            model_name='tramovuelo',
            name='descripcion_carga',
            field=models.TextField(blank=True, help_text='Descripción detallada de la carga transportada en este tramo.', null=True, verbose_name='Descripción de la Carga'),
        ),
        migrations.AddField(
            model_name='tramovuelo',
            name='facturacion',
            field=models.CharField(choices=[('factura', 'Factura'), ('no_factura', 'No Factura'), ('colaboracion', 'Colaboración')], default='no_factura', max_length=20, verbose_name='Opciones de Facturación'),
        ),
        migrations.AddField(
            model_name='tramovuelo',
            name='tipo_carga',
            field=models.CharField(choices=[('pasajeros', 'Pasajeros'), ('mercancia', 'Mercancía'), ('mixto', 'Mixto')], default='pasajeros', max_length=10, verbose_name='Tipo de Carga'),
        ),
        migrations.AddField(
            model_name='tramovuelo',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10, verbose_name='Tipo de Pago'),
        ),
        migrations.AddField(
            model_name='tramovuelo',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Selecciona el cliente para este tramo si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_vuelos.cliente', verbose_name='Cliente'),
        ),
    ]
