# Generated by Django 5.1.4 on 2025-01-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0020_cliente_inventariooro_tramovuelo_descripcion_carga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramovuelo',
            name='pago_en_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pago en gramos de oro'),
        ),
    ]
