# Generated by Django 5.1.4 on 2025-01-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0021_tramovuelo_pago_en_gramos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='notas',
        ),
        migrations.AddField(
            model_name='cliente',
            name='deuda_dolares',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deuda en Dólares'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='deuda_euros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deuda en Euros'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gramos_por_ingresar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gramos de Oro por Ingresar'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='deuda_gramos_oro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deuda Total en Gramos de Oro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='deuda_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deuda Total en Moneda'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del Cliente'),
        ),
    ]
