# Generated by Django 5.1.4 on 2025-01-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0022_remove_cliente_contacto_remove_cliente_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariooro',
            name='gramos_disponibles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventariooro',
            name='gramos_en_fundicion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventariooro',
            name='precio_por_gramo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventariooro',
            name='valor_total_usd',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
