# Generated by Django 5.1.4 on 2025-01-09 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0023_alter_inventariooro_gramos_disponibles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='vuelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramos_vuelo', to='registro_vuelos.vuelo'),
        ),
    ]
