# Generated by Django 5.1.4 on 2025-01-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0024_alter_vuelo_options_alter_tramovuelo_vuelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={},
        ),
    ]
