# Generated by Django 5.1.4 on 2025-01-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0025_alter_vuelo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramovuelo',
            options={},
        ),
    ]
