# Generated by Django 5.1.4 on 2025-01-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0027_alter_tramovuelo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramovuelo',
            options={},
        ),
    ]
