# Generated by Django 5.1.4 on 2025-01-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0028_alter_tramovuelo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramovuelo',
            options={'verbose_name': 'Tramo de Vuelo', 'verbose_name_plural': 'Tramos de Vuelo'},
        ),
    ]
