# Generated by Django 5.1.4 on 2025-01-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0029_alter_tramovuelo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramovuelo',
            options={},
        ),
    ]
