# Generated by Django 5.1.4 on 2025-01-12 16:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0030_alter_tramovuelo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramovuelo',
            name='horas_tramo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
    ]
