# Generated by Django 5.1.4 on 2025-01-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0031_alter_tramovuelo_horas_tramo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vuelo',
            options={'verbose_name': 'Vuelo', 'verbose_name_plural': 'Vuelos'},
        ),
    ]
