# Generated by Django 5.1.4 on 2025-01-12 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0032_alter_vuelo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariooro',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventariooro',
            name='gramos_disponibles',
        ),
        migrations.RemoveField(
            model_name='inventariooro',
            name='gramos_en_fundicion',
        ),
        migrations.AddField(
            model_name='inventariooro',
            name='gramos_ajustados_polvo',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Gramos Ajustados (Polvo)'),
        ),
        migrations.AddField(
            model_name='inventariooro',
            name='gramos_cobrados_polvo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gramos Cobrados (Polvo)'),
        ),
        migrations.AddField(
            model_name='inventariooro',
            name='gramos_disponibles_polvo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gramos Disponibles (Polvo)'),
        ),
        migrations.AddField(
            model_name='inventariooro',
            name='gramos_por_cobrar_polvo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gramos por Cobrar (Polvo)'),
        ),
        migrations.AlterField(
            model_name='inventariooro',
            name='precio_por_gramo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por Gramo'),
        ),
        migrations.AlterField(
            model_name='inventariooro',
            name='valor_total_usd',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Valor Total (USD)'),
        ),
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de la Barra')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso en Gramos')),
                ('ley', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Ley (Pureza)')),
                ('gramos_puros', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Gramos Puros')),
                ('fecha_generacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('vendida', models.BooleanField(default=False, verbose_name='¿Vendida?')),
                ('precio_venta_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de Venta (USD)')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barras', to='registro_vuelos.inventariooro', verbose_name='Inventario Asociado')),
            ],
        ),
    ]
