# Generated by Django 5.1.4 on 2025-01-18 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0033_alter_inventariooro_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramovuelo',
            options={'verbose_name': 'Tramo de Vuelo', 'verbose_name_plural': 'Tramos de Vuelo'},
        ),
        migrations.RemoveField(
            model_name='inventariooro',
            name='gramos_cobrados_polvo',
        ),
        migrations.CreateModel(
            name='TrayectoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_trayecto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del Trayecto')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectos_llegada', to='registro_vuelos.destino', verbose_name='Destino de Llegada')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectos_costo', to='registro_vuelos.empleado', verbose_name='Empleado (Piloto o Copiloto)')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectos_salida', to='registro_vuelos.destino', verbose_name='Destino de Origen')),
            ],
            options={
                'verbose_name': 'Trayecto de Costo',
                'verbose_name_plural': 'Trayectos de Costo',
                'unique_together': {('empleado', 'origen', 'destino')},
            },
        ),
        migrations.DeleteModel(
            name='DestinoCosto',
        ),
    ]
