# Generated by Django 5.1.4 on 2025-01-18 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0034_alter_tramovuelo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramovuelo',
            name='trayecto_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramos_relacionados', to='registro_vuelos.trayectocosto'),
        ),
    ]
