# Generated by Django 5.1.4 on 2025-01-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0035_tramovuelo_trayecto_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramovuelo',
            name='trayecto_costo',
        ),
    ]
