# Generated by Django 5.1.4 on 2025-01-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0036_remove_tramovuelo_trayecto_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Moneda')),
                ('simbolo', models.CharField(help_text='Ejemplo: USD, EUR', max_length=10, verbose_name='Símbolo')),
                ('tasa_conversion', models.DecimalField(decimal_places=4, help_text='Cantidad de esta moneda equivalente a 1 dólar.', max_digits=10, verbose_name='Tasa de Conversión a Dólares')),
            ],
        ),
        migrations.AddField(
            model_name='tramovuelo',
            name='cantidad_moneda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad en Moneda'),
        ),
        migrations.AddField(
            model_name='tramovuelo',
            name='forma_pago',
            field=models.CharField(choices=[('moneda', 'Moneda'), ('gramos', 'Gramos'), ('no_aplica', 'No Aplica')], default='gramos', max_length=10, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='tramovuelo',
            name='monto_en_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automáticamente según la tasa de cambio.', max_digits=10, null=True, verbose_name='Monto en Dólares'),
        ),
        migrations.AddField(
            model_name='tramovuelo',
            name='tasa_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de cambio para convertir la moneda seleccionada a dólares.', max_digits=10, null=True, verbose_name='Tasa de Cambio'),
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito'), ('no_aplica', 'No Aplica')], default='contado', max_length=10, verbose_name='Tipo de Pago'),
        ),
        migrations.AddField(
            model_name='tramovuelo',
            name='moneda',
            field=models.ForeignKey(blank=True, help_text='Selecciona la moneda utilizada para el pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_vuelos.moneda', verbose_name='Moneda'),
        ),
    ]
