# Generated by Django 5.1.4 on 2025-01-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0037_moneda_tramovuelo_cantidad_moneda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneda',
            name='tasa_conversion',
        ),
    ]
