# Generated by Django 5.1.4 on 2025-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0038_remove_moneda_tasa_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramovuelo',
            name='pago_en_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto'),
        ),
    ]
