# Generated by Django 5.1.4 on 2025-01-23 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0039_alter_tramovuelo_pago_en_gramos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('balance_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('transferencia', 'Transferencia')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='registro_vuelos.cajachica')),
                ('caja_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='registro_vuelos.cajachica')),
            ],
        ),
    ]
