# Generated by Django 5.1.4 on 2025-01-23 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0040_cajachica_movimientocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Gasto'), ('transferencia', 'Transferencia')], max_length=50),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='cuenta_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='registro_vuelos.cuentagasto'),
        ),
    ]
