# Generated by Django 5.1.4 on 2025-01-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0042_cuentagasto_balance_total_movimientogasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramovuelo',
            name='caja',
            field=models.ForeignKey(blank=True, help_text='Selecciona la caja a afectar para pagos en moneda (contado).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_vuelos.cajachica', verbose_name='Caja Asociada'),
        ),
    ]
