# Generated by Django 5.1.4 on 2025-01-25 17:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0043_tramovuelo_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramovuelo',
            name='pago_en_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Monto'),
        ),
    ]
