# Generated by Django 5.1.4 on 2025-01-26 11:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0044_alter_tramovuelo_pago_en_gramos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='deuda_dolares',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='deuda_euros',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='gramos_por_ingresar',
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_generado_dolares',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Generado en Dolares'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_generado_gramos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Generado en Gramos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='deuda_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Deuda Total en Dólares'),
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='pago_en_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Monto en Gramos'),
        ),
        migrations.CreateModel(
            name='HistorialTransacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('abono_moneda', 'Abono en Moneda'), ('abono_gramos', 'Abono en Gramos'), ('vuelo_contado', 'Vuelo Contado')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='registro_vuelos.cliente')),
            ],
        ),
    ]
