# Generated by Django 5.1.4 on 2025-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0045_remove_cliente_deuda_dolares_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialtransacciones',
            options={'verbose_name': 'Historial de Transacciones', 'verbose_name_plural': 'Historial de Transacciones'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='total_generado_dolares',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Generado en Dólares'),
        ),
        migrations.AlterField(
            model_name='historialtransacciones',
            name='tipo',
            field=models.CharField(choices=[('abono_moneda', 'Abono en Moneda'), ('abono_gramos', 'Abono en Gramos'), ('vuelo_contado', 'Vuelo Contado')], max_length=50, verbose_name='Tipo de Transacción'),
        ),
    ]
