# Generated by Django 5.1.4 on 2025-01-28 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0047_seriefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramovuelo',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='serie_factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registro_vuelos.seriefactura'),
        ),
    ]
