# Generated by Django 5.1.4 on 2025-01-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0048_tramovuelo_numero_factura_vuelo_numero_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramovuelo',
            name='monto_en_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tramovuelo',
            name='forma_pago',
            field=models.CharField(choices=[('moneda', 'Moneda'), ('gramos', 'Gramos'), ('no_aplica', 'No Aplica')], max_length=20),
        ),
    ]
