# Generated by Django 5.1.4 on 2025-01-31 18:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0049_tramovuelo_monto_en_gramos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramovuelo',
            name='incremento_horometro',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Incremento del Horómetro'),
        ),
    ]
