# Generated by Django 5.1.4 on 2025-01-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0050_tramovuelo_incremento_horometro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramovuelo',
            name='gramos_aplicados',
            field=models.BooleanField(default=False),
        ),
    ]
