# Generated by Django 5.1.4 on 2025-02-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0051_tramovuelo_gramos_aplicados'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='horometro_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Introduce el horómetro del avión al momento de su registro.', max_digits=10, verbose_name='Horómetro Inicial'),
        ),
    ]
