# Generated by Django 5.1.4 on 2025-02-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0052_avion_horometro_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramovuelo',
            name='vuelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramos_vuelo', to='registro_vuelos.vuelo'),
        ),
    ]
