# Generated by Django 5.1.4 on 2025-02-26 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0053_alter_tramovuelo_vuelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('tipo_pago', models.CharField(choices=[('por_hora', 'Pago por Hora'), ('por_destino', 'Pago por Destino'), ('colaboracion', 'Pago por Colaboración')], max_length=20)),
                ('horas_pagadas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_por_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='registro_vuelos.empleado')),
            ],
            options={
                'verbose_name': 'Pago a Empleado',
                'verbose_name_plural': 'Pagos a Empleados',
            },
        ),
        migrations.CreateModel(
            name='SaldoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_pendientes_por_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_pendientes_por_destino', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_pendientes_colaboracion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_pendiente_por_destino', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_horas_pagadas_por_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_horas_pagadas_por_destino', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_horas_pagadas_colaboracion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_costo_pagado_por_destino', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo', to='registro_vuelos.empleado')),
            ],
        ),
    ]
