# Generated by Django 5.1.4 on 2025-03-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vuelos', '0054_pagoempleado_saldoempleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldoempleado',
            options={'verbose_name': 'Empleados - Saldos', 'verbose_name_plural': 'Empleados - Saldos'},
        ),
    ]
